##TOP 500 MOVIES BY PRODUCTION BUDGET

##BUSINESS UNDERSTANDING

#Business Objective

Tujuan utama proyek ini adalah untuk mengetahui film dengan budget produksi terbesar yang akan digunakan untuk mendukung inovasi, kreatifitas, dan keberlangsungan dalam menjaga kualitas industri per film an. Hal ini meliputi budget produksi, hasil penjualan tiket film, genre film, waktu tayang, dan rating umur film. Hal ini dilakukan agar dapat meningkatkan efesiensi budget dan menetapkan target penonton yang tepat.

#Assess Situation

Situasi bisnis yang mendasari analisis ini adalah karena industri film yang dinamis yang selalu berubah. Perubahan tren penonton, preferensi genre mengharuskan produsen film untuk memiliki pemahaman yang mendalam tentang kondisi industri film. Pada saat ini tidak serta merta hanya dengan mengeluarkan dana yang besar kita dapat langsung membuat film yang bisa meningkatkan penjualan tiket, kita harus tau preferensi genre yang diinginkan para penonton agar bisa berinovasi dan meningkatkan kualitas film sesuai dengan budget yang diperlukan

#Data Mining Goals

Mengidentifikasi sejumlah film untuk mendapatkan data yang akan membantu efesiensi budget dan pertumbuhan berkelanjutan dengan mengamati budget produksi, hasil penjualan, pendapatan bersih, waktu tayang, jumlah bioskop yang menayangkan, dan rating umur film untuk mendapatkan pemahaman yang lebih mendalam mengenai industri film

#Project Plan

Proyek ini bertujuan untuk menganalisis dan memberikan insight tentang tren industri film berdasarkan anggaran produksi, dengan menggunakan data dari 500 film dengan anggaran tertinggi. Dengan melihat hubungan antara anggaran produksi, pendapatan, genre, dan tahun rilis, kita bisa menganalisis pola-pola yang penting, seperti dampak judul besar, anggaran besar, jumlah bioskop, serta genre. Hasil analisis ini diharapkan dapat menjadi panduan bagi para produsen film dalam industri film untuk membuat keputusan strategis yang lebih terinformasi dan efektif.

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("top-500-movies.csv")

df

,rank,release_date,title,url,production_cost,domestic_gross,worldwide_gross,opening_weekend,mpaa,genre,theaters,runtime,year
0,1,2019-04-23,Avengers: Endgame,/movie/Avengers-Endgame-(2019)#tab=summary,400000000,858373000,2797800564,357115007.0,PG-13,Action,4662.0,181.0,2019.0
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,/movie/Pirates-of-the-Caribbean-On-Stranger-Ti...,379000000,241071802,1045713802,90151958.0,PG-13,Adventure,4164.0,136.0,2011.0
2,3,2015-04-22,Avengers: Age of Ultron,/movie/Avengers-Age-of-Ultron#tab=summary,365000000,459005868,1395316979,191271109.0,PG-13,Action,4276.0,141.0,2015.0
3,4,2015-12-16,Star Wars Ep. VII: The Force Awakens,/movie/Star-Wars-Ep-VII-The-Force-Awakens#tab=...,306000000,936662225,2064615817,247966675.0,PG-13,Adventure,4134.0,136.0,2015.0
4,5,2018-04-25,Avengers: Infinity War,/movie/Avengers-Infinity-War#tab=summary,300000000,678815482,2048359754,257698183.0,PG-13,Action,4474.0,156.0,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,2013-02-06,A Good Day to Die Hard,/movie/Die-Hard-5#tab=summary,92000000,67349198,304249198,24834845.0,R,Action,3555.0,98.0,2013.0
496,497,2004-04-09,The Alamo,/movie/Alamo-The-(2004)#tab=summary,92000000,22406362,23911362,9124701.0,PG-13,Western,2609.0,137.0,2004.0
497,498,1995-12-22,Cutthroat Island,/movie/Cutthroat-Island#tab=summary,92000000,10017322,18517322,2371415.0,PG-13,Adventure,1619.0,NaN,1995.0
498,499,2013-12-19,The Secret Life of Walter Mitty,/movie/Secret-Life-of-Walter-Mitty-The-(2012)#...,91000000,58236838,187861183,12765508.0,PG,Adventure,2922.0,114.0,2013.0
499,500,2023-03-09,65,/movie/65-(2022)#tab=summary,91000000,0,0,NaN,NaN,Thriller/Suspense,NaN,NaN,2023.0

#DATA UNDERSTANDING

data diambil dari masing-masing movie page dan menggunakan rvest https://rvest.tidyverse.org/. Jenis data merupakan kuantitatif, kualitatif, dan rasio. Untuk dataset berasal dari https://www.kaggle.com/datasets/mitchellharrison/top-500-movies-budget/data

tipe data

In [33]:
df.dtypes

rank                 int64
release_date        object
title               object
url                 object
production_cost      int64
domestic_gross       int64
worldwide_gross      int64
opening_weekend    float64
mpaa                object
genre               object
theaters           float64
runtime            float64
year               float64
dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             500 non-null    int64
 1   release_date     499 non-null    object
 2   title            500 non-null    object
 3   url              500 non-null    object
 4   production_cost  500 non-null    int64
 5   domestic_gross   500 non-null    int64
 6   worldwide_gross  500 non-null    int64
 7   opening_weekend  479 non-null    float64
 8   mpaa             492 non-null    object
 9   genre            495 non-null    object
 10  theaters         479 non-null    float64
 11  runtime          487 non-null    float64
 12  year             499 non-null    float64
dtypes: float64(4), int64(4), object(5)
memory usage: 50.9+ KB

In [34]:
df.describe()

,rank,production_cost,domestic_gross,worldwide_gross,opening_weekend,theaters,runtime,year
count,500.000000,5.000000e+02,5.000000e+02,5.000000e+02,4.790000e+02,479.000000,487.000000,499.000000
mean,250.500000,1.494954e+08,1.696114e+08,4.697776e+08,5.429206e+07,3659.770355,121.885010,2011.394790
std,144.481833,4.774040e+07,1.421642e+08,3.850620e+08,4.619796e+07,546.018902,22.399642,6.560688
min,1.000000,9.100000e+07,0.000000e+00,0.000000e+00,4.855800e+04,30.000000,76.000000,1991.000000
25%,125.750000,1.100000e+08,7.047110e+07,2.122188e+08,2.421873e+07,3378.500000,104.500000,2007.000000
50%,250.500000,1.400000e+08,1.318470e+08,3.671458e+08,4.167120e+07,3735.000000,120.000000,2012.000000
75%,375.250000,1.750000e+08,2.185998e+08,6.484251e+08,6.812391e+07,4065.000000,135.000000,2016.000000
max,500.000000,4.000000e+08,9.366622e+08,2.910371e+09,3.571150e+08,4802.000000,210.000000,2023.000000

In [36]:
df.value_counts()

rank  release_date  title                            url                                                        production_cost  domestic_gross  worldwide_gross  opening_weekend  mpaa   genre      theaters  runtime  year
1     2019-04-23    Avengers: Endgame                /movie/Avengers-Endgame-(2019)#tab=summary                 400000000        858373000       2797800564       357115007.0      PG-13  Action     4662.0    181.0    2019.0    1
326   2016-12-29    Monster Trucks                   /movie/Monster-Trucks#tab=summary                          125000000        33370166        61642798         10950705.0       PG-13  Adventure  3119.0    104.0    2016.0    1
338   2013-08-09    Elysium                          /movie/Elysium#tab=summary                                 120000000        93050117        286192091        29807393.0       R      Action     3284.0    109.0    2013.0    1
337   2003-06-27    Charlie's Angels: Full Throttle  /movie/Charlies-Angels-Full-Throttle#tab=summary           120000000        100814328       227163273        37634221.0       PG-13  Action     3485.0    106.0    2003.0    1
336   2018-04-09    Rampage                          /movie/Rampage-(2018)#tab=summary                          120000000        101028233       427947217        35753093.0       PG-13  Action     4115.0    107.0    2018.0    1
                                                                                                                                                                                                                                 ..
162   2012-11-01    Wreck-It Ralph                   /movie/Wreck-It-Ralph#tab=summary                          165000000        189412677       496511521        49038712.0       PG     Adventure  3752.0    101.0    2012.0    1
161   2010-03-26    How to Train Your Dragon         /movie/How-to-Train-Your-Dragon#tab=summary                165000000        217581232       494870992        43732319.0       PG     Adventure  4060.0    91.0     2010.0    1
160   2014-10-25    Big Hero 6                       /movie/Big-Hero-6#tab=summary                              165000000        222527828       648415024        56215889.0       PG     Adventure  3773.0    108.0    2014.0    1
159   2016-10-24    Doctor Strange                   /movie/Doctor-Strange-(2016)#tab=summary                   165000000        232641920       676354481        85058311.0       PG-13  Action     3882.0    115.0    2016.0    1
499   2013-12-19    The Secret Life of Walter Mitty  /movie/Secret-Life-of-Walter-Mitty-The-(2012)#tab=summary  91000000         58236838        187861183        12765508.0       PG     Adventure  2922.0    114.0    2013.0    1
Name: count, Length: 474, dtype: int64

In [37]:
df.corr(numeric_only=True)

,rank,production_cost,domestic_gross,worldwide_gross,opening_weekend,theaters,runtime,year
rank,1.000000,-0.921557,-0.460587,-0.492761,-0.520052,-0.547803,-0.219339,-0.296317
production_cost,-0.921557,1.000000,0.485815,0.537454,0.579395,0.502060,0.273057,0.289846
domestic_gross,-0.460587,0.485815,1.000000,0.930380,0.886058,0.544418,0.262348,0.041829
worldwide_gross,-0.492761,0.537454,0.930380,1.000000,0.822920,0.536755,0.313970,0.104909
opening_weekend,-0.520052,0.579395,0.886058,0.822920,1.000000,0.615205,0.261564,0.209180
theaters,-0.547803,0.502060,0.544418,0.536755,0.615205,1.000000,-0.012624,0.509213
runtime,-0.219339,0.273057,0.262348,0.313970,0.261564,-0.012624,1.000000,0.003725
year,-0.296317,0.289846,0.041829,0.104909,0.209180,0.509213,0.003725,1.000000

#DATA CLEANING

In [38]:
print((df.isna().sum() / len(df)) * 100)

rank               0.0
release_date       0.2
title              0.0
url                0.0
production_cost    0.0
domestic_gross     0.0
worldwide_gross    0.0
opening_weekend    4.2
mpaa               1.6
genre              1.0
theaters           4.2
runtime            2.6
year               0.2
dtype: float64

In [39]:
df[df['release_date'].isnull()]

,rank,release_date,title,url,production_cost,domestic_gross,worldwide_gross,opening_weekend,mpaa,genre,theaters,runtime,year
260,261,NaN,Desert Warrior,/movie/Desert-Warrior-(2022-Saudi-Arabia)#tab=...,140000000,0,0,NaN,NaN,NaN,NaN,NaN,NaN

tidak perlu diperbaiki karena film belum tayang

In [40]:
df[df['opening_weekend'].isnull()]

,rank,release_date,title,url,production_cost,domestic_gross,worldwide_gross,opening_weekend,mpaa,genre,theaters,runtime,year
8,9,2023-07-11,Mission: Impossible Dead Reckoning Part One,/movie/Mission-Impossible-Dead-Reckoning-Part-...,290000000,0,0,NaN,NaN,Action,NaN,NaN,2023.0
83,84,2020-09-04,Mulan,/movie/Mulan-(2020)#tab=summary,200000000,0,69965374,NaN,PG-13,Adventure,NaN,115.0,2020.0
84,85,2021-07-02,The Tomorrow War,/movie/Tomorrow-War-The#tab=summary,200000000,0,19220000,NaN,PG-13,Action,NaN,140.0,2021.0
85,86,2022-07-13,The Gray Man,/movie/Gray-Man-The-(2022)#tab=summary,200000000,0,451178,NaN,PG-13,Thriller/Suspense,NaN,129.0,2022.0
109,110,2005-12-09,"The Chronicles of Narnia: The Lion, the Witch a…",/movie/Chronicles-of-Narnia-The-Lion-the-Witch...,180000000,291710957,720539572,NaN,NaN,NaN,NaN,NaN,2005.0
140,141,2022-03-10,Turning Red,/movie/Turning-Red-(2022)#tab=summary,175000000,0,10965045,NaN,PG,Adventure,NaN,100.0,2022.0
179,180,2019-11-01,The Irishman,/movie/Irishman-The-(2019)#tab=summary,159000000,0,910234,NaN,R,Drama,NaN,210.0,2019.0
181,182,2010-12-10,The Chronicles of Narnia: The Voyage of the Daw…,/movie/Chronicles-of-Narnia-The-Voyage-of-the-...,155000000,104386950,418186950,NaN,NaN,NaN,NaN,NaN,2010.0
234,235,2021-11-04,Red Notice,/movie/Red-Notice-(2020)#tab=summary,150000000,0,173638,NaN,PG-13,Action,NaN,115.0,2021.0
235,236,2019-12-13,6 Underground,/movie/6-Underground-(2019)#tab=summary,150000000,0,0,NaN,R,Action,NaN,128.0,2019.0
246,247,2003-07-09,Pirates of the Caribbean: The Curse of the Blac…,/movie/Pirates-of-the-Caribbean-The-Curse-of-t...,140000000,305410819,654310819,NaN,NaN,NaN,NaN,NaN,2003.0
260,261,NaN,Desert Warrior,/movie/Desert-Warrior-(2022-Saudi-Arabia)#tab=...,140000000,0,0,NaN,NaN,NaN,NaN,NaN,NaN
343,344,2015-08-05,The Fantastic Four,/movie/Fantastic-Four-The-(2015)#tab=summary,120000000,56117548,167849187,NaN,NaN,NaN,NaN,NaN,2015.0
347,348,2018-11-09,Outlaw King,/movie/Outlaw-King-(2018)#tab=summary,120000000,0,0,NaN,R,Action,NaN,117.0,2018.0
348,349,2022-12-02,Emancipation,/movie/Emancipation-(2022)#tab=summary,120000000,0,0,NaN,NaN,Thriller/Suspense,NaN,132.0,2022.0
350,351,2021-01-25,Tang Ren Jie Tan An 3,/movie/Tang-Ren-Jie-Tan-An-3-(China)#tab=summary,117000000,0,699084069,NaN,R,Action,NaN,136.0,2021.0
360,361,2019-03-06,Triple Frontier,/movie/Triple-Frontier-(2019)#tab=summary,115000000,0,0,NaN,R,Action,NaN,125.0,2019.0
361,362,2008-07-04,Astérix aux Jeux Olympiques,/movie/Asterix-aux-Jeux-Olympiques#tab=summary,113500000,999811,132999811,NaN,Unrated,Adventure,NaN,NaN,2008.0
464,465,2020-12-09,The Midnight Sky,/movie/Midnight-Sky-The-(2020)#tab=summary,100000000,0,75615,NaN,PG-13,Adventure,NaN,118.0,2020.0
465,466,2020-06-12,Artemis Fowl,/movie/Artemis-Fowl-(2020)#tab=summary,100000000,0,0,NaN,PG,Adventure,NaN,115.0,2020.0
499,500,2023-03-09,65,/movie/65-(2022)#tab=summary,91000000,0,0,NaN,NaN,Thriller/Suspense,NaN,NaN,2023.0

In [41]:
df['opening_weekend'] = df['opening_weekend'].fillna(df['opening_weekend'].dropna().mean())

In [42]:
df[df['runtime'].isnull()]

,rank,release_date,title,url,production_cost,domestic_gross,worldwide_gross,opening_weekend,mpaa,genre,theaters,runtime,year
8,9,2023-07-11,Mission: Impossible Dead Reckoning Part One,/movie/Mission-Impossible-Dead-Reckoning-Part-...,290000000,0,0,5.429206e+07,NaN,Action,NaN,NaN,2023.0
78,79,2022-04-06,Fantastic Beasts: The Secrets of Dumbledore,/movie/Fantastic-Beasts-The-Secrets-of-Dumbled...,200000000,95850844,404560146,4.215126e+07,PG-13,Adventure,4245.0,NaN,2022.0
109,110,2005-12-09,"The Chronicles of Narnia: The Lion, the Witch a…",/movie/Chronicles-of-Narnia-The-Lion-the-Witch...,180000000,291710957,720539572,5.429206e+07,NaN,NaN,NaN,NaN,2005.0
177,178,2006-05-12,Poseidon,/movie/Poseidon#tab=summary,160000000,60674817,181674817,2.215541e+07,PG-13,Adventure,3555.0,NaN,2006.0
181,182,2010-12-10,The Chronicles of Narnia: The Voyage of the Daw…,/movie/Chronicles-of-Narnia-The-Voyage-of-the-...,155000000,104386950,418186950,5.429206e+07,NaN,NaN,NaN,NaN,2010.0
246,247,2003-07-09,Pirates of the Caribbean: The Curse of the Blac…,/movie/Pirates-of-the-Caribbean-The-Curse-of-t...,140000000,305410819,654310819,5.429206e+07,NaN,NaN,NaN,NaN,2003.0
260,261,NaN,Desert Warrior,/movie/Desert-Warrior-(2022-Saudi-Arabia)#tab=...,140000000,0,0,5.429206e+07,NaN,NaN,NaN,NaN,NaN
343,344,2015-08-05,The Fantastic Four,/movie/Fantastic-Four-The-(2015)#tab=summary,120000000,56117548,167849187,5.429206e+07,NaN,NaN,NaN,NaN,2015.0
361,362,2008-07-04,Astérix aux Jeux Olympiques,/movie/Asterix-aux-Jeux-Olympiques#tab=summary,113500000,999811,132999811,5.429206e+07,Unrated,Adventure,NaN,NaN,2008.0
403,404,2001-04-27,Town & Country,/movie/Town-and-Country#tab=summary,105000000,6712451,10364769,3.029858e+06,R,Romantic Comedy,2222.0,NaN,2001.0
462,463,2002-08-16,The Adventures of Pluto Nash,/movie/Adventures-of-Pluto-Nash-The#tab=summary,100000000,4411102,7094995,2.182900e+06,PG-13,Comedy,2320.0,NaN,2002.0
497,498,1995-12-22,Cutthroat Island,/movie/Cutthroat-Island#tab=summary,92000000,10017322,18517322,2.371415e+06,PG-13,Adventure,1619.0,NaN,1995.0
499,500,2023-03-09,65,/movie/65-(2022)#tab=summary,91000000,0,0,5.429206e+07,NaN,Thriller/Suspense,NaN,NaN,2023.0

In [43]:
df['runtime'] = df['runtime'].fillna(df['runtime'].dropna().mean())

In [44]:
pd.DataFrame(df.isna().sum() / len(df) * 100, columns=['Null Ratio %'])

                 Null Ratio %
rank                      0.0
release_date              0.2
title                     0.0
url                       0.0
production_cost           0.0
domestic_gross            0.0
worldwide_gross           0.0
opening_weekend           0.0
mpaa                      1.6
genre                     1.0
theaters                  4.2
runtime                   0.0
year                      0.2

In [45]:
df[df.duplicated()]

Empty DataFrame
Columns: [rank, release_date, title, url, production_cost, domestic_gross, worldwide_gross, opening_weekend, mpaa, genre, theaters, runtime, year]
Index: []

#OUTLIERS

In [46]:
results = []

cols = df.select_dtypes(include=['float64', 'int64'])

for col in cols:
  q1 = df[col].quantile(0.25)
  q3 = df[col].quantile(0.75)
  iqr = q3 - q1
  lower_bound = q1 - 1.5*iqr
  upper_bound = q3 + 1.5*iqr
  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
  percent_outliers = (len(outliers)/len(df))*100
  results.append({'Kolom': col, 'Persentase Outliers': percent_outliers})

results_df = pd.DataFrame(results)
results_df.set_index('Kolom', inplace=True)
results_df = results_df.rename_axis(None, axis=0).rename_axis('Kolom', axis=1)

display(results_df)

Kolom            Persentase Outliers
rank                             0.0
production_cost                  2.2
domestic_gross                   4.4
worldwide_gross                  3.4
opening_weekend                  7.2
theaters                         2.0
runtime                          1.4
year                             0.2

#CONSTRUCT DATA
Kita akan membuat kolom baru yaitu pendapatan bersih dari movie yang telah ditayangkan

In [47]:
df["net_income"] = df["worldwide_gross"] - df["production_cost"]
df

,rank,release_date,title,url,production_cost,domestic_gross,worldwide_gross,opening_weekend,mpaa,genre,theaters,runtime,year,net_income
0,1,2019-04-23,Avengers: Endgame,/movie/Avengers-Endgame-(2019)#tab=summary,400000000,858373000,2797800564,3.571150e+08,PG-13,Action,4662.0,181.00000,2019.0,2397800564
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,/movie/Pirates-of-the-Caribbean-On-Stranger-Ti...,379000000,241071802,1045713802,9.015196e+07,PG-13,Adventure,4164.0,136.00000,2011.0,666713802
2,3,2015-04-22,Avengers: Age of Ultron,/movie/Avengers-Age-of-Ultron#tab=summary,365000000,459005868,1395316979,1.912711e+08,PG-13,Action,4276.0,141.00000,2015.0,1030316979
3,4,2015-12-16,Star Wars Ep. VII: The Force Awakens,/movie/Star-Wars-Ep-VII-The-Force-Awakens#tab=...,306000000,936662225,2064615817,2.479667e+08,PG-13,Adventure,4134.0,136.00000,2015.0,1758615817
4,5,2018-04-25,Avengers: Infinity War,/movie/Avengers-Infinity-War#tab=summary,300000000,678815482,2048359754,2.576982e+08,PG-13,Action,4474.0,156.00000,2018.0,1748359754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,2013-02-06,A Good Day to Die Hard,/movie/Die-Hard-5#tab=summary,92000000,67349198,304249198,2.483484e+07,R,Action,3555.0,98.00000,2013.0,212249198
496,497,2004-04-09,The Alamo,/movie/Alamo-The-(2004)#tab=summary,92000000,22406362,23911362,9.124701e+06,PG-13,Western,2609.0,137.00000,2004.0,-68088638
497,498,1995-12-22,Cutthroat Island,/movie/Cutthroat-Island#tab=summary,92000000,10017322,18517322,2.371415e+06,PG-13,Adventure,1619.0,121.88501,1995.0,-73482678
498,499,2013-12-19,The Secret Life of Walter Mitty,/movie/Secret-Life-of-Walter-Mitty-The-(2012)#...,91000000,58236838,187861183,1.276551e+07,PG,Adventure,2922.0,114.00000,2013.0,96861183
499,500,2023-03-09,65,/movie/65-(2022)#tab=summary,91000000,0,0,5.429206e+07,NaN,Thriller/Suspense,NaN,121.88501,2023.0,-91000000

#DATA REDUCTION
Menghapus kolom yang kurang relevan dengan studi kasus

In [48]:
df = df.drop('url', axis=1)

In [49]:
df

,rank,release_date,title,production_cost,domestic_gross,worldwide_gross,opening_weekend,mpaa,genre,theaters,runtime,year,net_income
0,1,2019-04-23,Avengers: Endgame,400000000,858373000,2797800564,3.571150e+08,PG-13,Action,4662.0,181.00000,2019.0,2397800564
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802,9.015196e+07,PG-13,Adventure,4164.0,136.00000,2011.0,666713802
2,3,2015-04-22,Avengers: Age of Ultron,365000000,459005868,1395316979,1.912711e+08,PG-13,Action,4276.0,141.00000,2015.0,1030316979
3,4,2015-12-16,Star Wars Ep. VII: The Force Awakens,306000000,936662225,2064615817,2.479667e+08,PG-13,Adventure,4134.0,136.00000,2015.0,1758615817
4,5,2018-04-25,Avengers: Infinity War,300000000,678815482,2048359754,2.576982e+08,PG-13,Action,4474.0,156.00000,2018.0,1748359754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,2013-02-06,A Good Day to Die Hard,92000000,67349198,304249198,2.483484e+07,R,Action,3555.0,98.00000,2013.0,212249198
496,497,2004-04-09,The Alamo,92000000,22406362,23911362,9.124701e+06,PG-13,Western,2609.0,137.00000,2004.0,-68088638
497,498,1995-12-22,Cutthroat Island,92000000,10017322,18517322,2.371415e+06,PG-13,Adventure,1619.0,121.88501,1995.0,-73482678
498,499,2013-12-19,The Secret Life of Walter Mitty,91000000,58236838,187861183,1.276551e+07,PG,Adventure,2922.0,114.00000,2013.0,96861183
499,500,2023-03-09,65,91000000,0,0,5.429206e+07,NaN,Thriller/Suspense,NaN,121.88501,2023.0,-91000000